/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
creating web directory ./results/ellen_dwt_uresnet2_3_512n1000_1016/test_latest
processing (0000)-th image... ['/home/guest1/ellen_data/UKB_quality_data2_combined/input_20220623_512_n1000/testA/0001.jpg']
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
processing (0005)-th image... ['/home/guest1/ellen_data/UKB_quality_data2_combined/input_20220623_512_n1000/testA/0006.jpg']
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
processing (0010)-th image... ['/home/guest1/ellen_data/UKB_quality_data2_combined/input_20220623_512_n1000/testA/0011.jpg']
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
processing (0015)-th image... ['/home/guest1/ellen_data/UKB_quality_data2_combined/input_20220623_512_n1000/testA/0016.jpg']
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
processing (0020)-th image... ['/home/guest1/ellen_data/UKB_quality_data2_combined/input_20220623_512_n1000/testA/0021.jpg']
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
========================================
hello!!!!!!!!
Traceback (most recent call last):
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/PIL/ImageFile.py", line 504, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test_intermediate.py", line 133, in <module>
    save_images_branch(webpage, fake_B_scattering, img_path, aspect_ratio=opt.aspect_ratio, width=opt.display_winsize, use_wandb=opt.use_wandb)
  File "test_intermediate.py", line 59, in save_images_branch
    util.save_image(im, save_path, aspect_ratio=aspect_ratio)
  File "/home/guest1/ellen_code/pytorch-CycleGAN-and-pix2pix_ellen/util/util.py", line 66, in save_image
    image_pil.save(image_path)
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/PIL/Image.py", line 2240, in save
    save_handler(self, fp, filename)
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 1348, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/guest1/.conda/envs/ellen/lib/python3.7/site-packages/PIL/ImageFile.py", line 518, in _save
    l, s, d = e.encode(bufsize)
KeyboardInterrupt